use_frameworks!

platform :ios, '9.0'

target 'SelectView_Example' do
  pod 'SelectView', :path => '../'

  target 'SelectView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
